[book]
authors = ["AntiSlop Contributors"]
language = "en"
src = "docs"
title = "AntiSlop Documentation"

[output.html]
git-repository-url = "https://github.com/skew202/antislop"
site-url = "/antislop/"
additional-css = ["docs/theme/custom.css"]
additional-js = ["docs/theme/mermaid-init.js"]

[preprocessor.index]
