[book]
title = "Antislop"
authors = ["Antislop Contributors"]
language = "en"
multilingual = false
src = "docs"

[build]
build-dir = "book"

[preprocessor]

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/user/antislop"
edit-url-template = "https://github.com/user/antislop/edit/main/docs/{path}"

[output.html.search]
limit-results = 30
